export let products = [
    {
        id: 1,
        title: "Adhesivo cementico manga Rapiretak ladrillos x 30Kg",
        price: 4.691,
        stock: 4,
        description: "Adhesivo para manga Rapiretak es un adhesivo cementicio en polvo compuesto especialmente para la ejecución de mamposterías de ladrillos de HCCA.",
        category: "construccion",
        img: "https://res.cloudinary.com/dhme3fmky/image/upload/v1689677332/Proyecto%20React%20CoderHouse/xgfza96yxwzkm6qu9kcu.jpg",
    },
    {
        id: 2,
        title: "Aditivo hidrofugo Ceresita C50 concentrado x 10Kg",
        price: 8.969,
        stock: 5,
        description: "Hidrófugo en pasta concentrado, formulado especialmente para agregar a mezclas cementicias y realizar aislaciones hidrófugas.",
        category: "construccion",
        img: "https://res.cloudinary.com/dhme3fmky/image/upload/v1689677332/Proyecto%20React%20CoderHouse/fssmlorsustmklsupdrc.jpg",
    },
    {
        id: 3,
        title: "Alambre de atar galvanizado N°16 x ø1.63mm x Kg",
        price: 1.439,
        stock: 10,
        description: "Cuenta con un galvanizado con capa de zinc que garantiza máxima durabilidad a la corrosión.",
        category: "construccion",
        img: "https://res.cloudinary.com/dhme3fmky/image/upload/v1689677332/Proyecto%20React%20CoderHouse/oshw7mukho7zjbnfkfby.jpg",
    },
    {
        id: 4,
        title: "Arena de puerto para construcción x 0.025m³",
        price: 494,
        stock: 5,
        description: "Arena de puerto para la construcción. Recomendada para mamposteria y hormigones de media exigencia, para la elaboración de adhesivos y revestimientos de media fineza.",
        category: "construccion",
        img: "https://res.cloudinary.com/dhme3fmky/image/upload/v1689677332/Proyecto%20React%20CoderHouse/d3zkra94602z9dx8tjcd.jpg",
    },
    {
        id: 5,
        title: "Accesorios de baño FV Arizona cromado brillante kit x 5u",
        price: 34.335,
        stock: 15,
        description: "Juego de 5 accesorios para baño en acero que incluye 1 percha simple, 1 toallero en aro, 1 jabonera, 1 Portarrollo y 1 porta cepillos de dientes.",
        category: "instalaciones_sanitarias",
        img: "https://res.cloudinary.com/dhme3fmky/image/upload/v1689677310/Proyecto%20React%20CoderHouse/rgvdbcfk8qszdyhrevnu.jpg",
    },    
    {
        id: 6,
        title: "Bacha de baño FERRUM Marina de apoyo",
        price: 268.905,
        stock: 5,
        description: "Lavatorio para colocar junto con mueble, de ceramica, para grifería monocomando. Se recomienda colocar con mueble de la misma línea. Incluye toallero barral cromado y botón de porcelana para desagüe. Sus dimensiones son 190mm x 482mm x 650mm",
        category: "instalaciones_sanitarias",
        img: "https://res.cloudinary.com/dhme3fmky/image/upload/v1689677332/Proyecto%20React%20CoderHouse/zklw4h3lq0t2fyfbey60.jpg",
    },
    {
        id: 7,
        title: "Rodillo multiuso N°22 lana natural línea Hobbista Premium 50mm x 220mm",
        price: 4.005,
        stock: 25,
        description: "Rodillo de lana pura procesada, de pelo largo intermedio de media densidad. El tubo es de 50mm, con mango ergonómico. Excelente acabado y fácil limpieza.",
        category: "pinturas_y_decoracion",
        img: "https://res.cloudinary.com/dhme3fmky/image/upload/v1689677332/Proyecto%20React%20CoderHouse/l1ungwfn7ooxqj72znqo.jpg",
    },

]